language: python
python:
  - "3.6"      # current default Python on Travis CI

compiler:
  - gcc
  - clang

sudo: required

matrix:
  include:
    # centos7
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 DOCKER=true
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 DOCKER=true TRIAL=true
    # with prefix
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 WEBPREFIX=/omero DOCKER=true
    # test remote
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 DOCKER=true ANSIBLE=true
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 WEBPREFIX=/omero DOCKER=true ANSIBLE=true
    # with cache
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 WEBSESSION=true DOCKER=true
    # ubuntu
    - os: linux
      dist: trusty
      env:
        - OS=ubuntu1604 ICEVER=3.6 DOCKER=true
    - os: linux
      dist: trusty
      env:
        - OS=ubuntu1804 ICEVER=3.6 DOCKER=true
    - os: linux
      dist: trusty
      env:
        - OS=ubuntu1804 ICEVER=3.6 DOCKER=true WEBSESSION=true
    # debian
    - os: linux
      dist: trusty
      env:
        - OS=debian9 ICEVER=3.6 DOCKER=true

before_install:
  - python --version
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh