language: generic

compiler:
  - gcc
  - clang

sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      language: docker
      env:
        - DOCKER=true OS=centos7 ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build
    - os: linux
      dist: trusty
      language: docker
      env:
        - DOCKER=true OS=centos7 ICEVER=3.5 OMEROVER=OMERO-DEV-breaking-build
    - os: linux
      dist: trusty
      language: docker
      env:
        - DOCKER=true OS=ubuntu ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build
    - os: osx
      osx_image: xcode7.3
      env:
        - DOCKER=false OS=osx ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build WEBPORT=8080 WEBPREFIX=/omero

before_install:
  - python --version
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh