language: generic

compiler:
  - gcc
  - clang

sudo: required

matrix:
  include:
    # centos7
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build DOCKER=true
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.5 OMEROVER=OMERO-DEV-breaking-build DOCKER=true
    # with prefix
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build WEBPREFIX=/omero DOCKER=true
    # test remote
    - os: linux
      dist: trusty
      env:
        - OS=centos7 ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build DOCKER=true ANSIBLE=true
    # ubuntu
    - os: linux
      dist: trusty
      env:
        - OS=ubuntu ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build DOCKER=true
    - os: osx
      osx_image: xcode7.3
      env:
        - OS=osx ICEVER=3.6 OMEROVER=OMERO-DEV-breaking-build WEBPORT=8080 WEBPREFIX=/omero

before_install:
  - python --version
  - ./.travis/before_install.sh

install:
  - ./.travis/install.sh

script:
  - ./.travis/script.sh