language: python
services:
  - docker
env:
  - OS=centos7 OMEROVER=OMERO-DEV-breaking-build

before_install:  
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine
  - sudo apt-get -y install shunit2
script:
    - OS=$OS OMEROVER=OMEROVER omeroweb/test/docker-build.sh
    - omeroweb/test/test_services.sh 
