---

- hosts: omeroweb-{{ os }}
  tasks:
    - name: Generate omeroweb-install-{{ os }}.sh
      template:
        src: "omeroweb-install.sh.j2"
        dest: "./omeroweb-install-{{ os }}"
        mode: a+x

    - name: Generate common/create_user.sh
      template:
        src: "common/create_user.sh.j2"
        dest: "./{{ os }}/create_user.sh"
        mode: a+x
    - name: Generate common/omeroweb_configure.sh
      template:
        src: "common/omeroweb_configure.sh.j2"
        dest: "./{{ os }}/omeroweb_configure.sh"
        mode: a+x
    - name: Generate common/virtualenv.sh
      template:
        src: "common/virtualenv.sh.j2"
        dest: "./{{ os }}/virtualenv.sh"
        mode: a+x
    - name: Generate common/websession_configure.sh
      template:
        src: "common/websession_configure.sh.j2"
        dest: "./{{ os }}/websession_configure.sh"
        mode: a+x
      when: web_session

    - name: Generate {{ os }}/deps.sh
      template:
        src: "{{ os }}/deps.sh.j2"
        dest: "./{{ os }}/deps.sh"
        mode: a+x
    - name: Generate {{ os }}/deps_ice.sh
      template:
        src: "{{ os }}/deps_ice.sh.j2"
        dest: "./{{ os }}/deps_ice.sh"
        mode: a+x
    - name: Generate {{ os }}/deps_web_session.sh
      template:
        src: "{{ os }}/deps_web_session.sh.j2"
        dest: "./{{ os }}/deps_web_session.sh"
        mode: a+x
      when: web_session

    - name: Generate {{ os }}/nginx.sh
      template:
        src: "{{ os }}/nginx.sh.j2"
        dest: "./{{ os }}/nginx.sh"
        mode: a+x

    - name: Generate {{ os }}/selinux.sh
      template:
        src: "{{ os }}/selinux.sh.j2"
        dest: "./{{ os }}/selinux.sh"
        mode: a+x
      when: selinux

    - name: Generate {{ os }}/daemon.sh
      template:
        src: "{{ os }}/daemon.sh.j2"
        dest: "./{{ os }}/daemon.sh"
        mode: a+x
      when: daemon

    - name: Generate omero-web-systemd.service.sh (centos7)
      template:
        src: "{{ os }}/omero-web-systemd.service.j2"
        dest: "./{{ os }}/omero-web-systemd.service"
      when: os=="centos7"
    - name: Generate omero-web-init.d (ubuntu)
      template:
        src: "{{ os }}/omero-web-init.d.j2"
        dest: "./{{ os }}/omero-web-init.d"
      when: os=="ubuntu"

    - name: Generate run.sh (ubuntu)
      template:
        src: "{{ os }}/run.sh.j2"
        dest: "./{{ os }}/run"
        mode: a+x
      when: os=="ubuntu" or os=="osx"

    - name: Generate init.sh (osx)
      template:
        src: "{{ os }}/init.sh.j2"
        dest: "./{{ os }}/init.sh"
        mode: a+x
      when: os=="osx"

#- include: omeroweb-install-doc.yml
#  vars:
#    doc: True
#    os: "{{ os }}"
